### ISSUE TITLE
FOUC when using animated views

### ISSUE THREAD

**Issue by kevin-smets** [tennisgent/angular-route-styles#1]
When your views are animated, you will see a FOUC. The view which is leaving, will be unstyled as the view css will be unloaded before it actually dissapears or animates out.

I currently don't have the time to get a plunkr up or anything, but I did get a solution going (coffeescript). I threw it into a directive though.

```coffee
"use strict"

define ["angular"], (angular) ->

  headDirective = ["$rootScope", "$compile", '$timeout', '$log', ($rootScope, $compile, $timeout, $log) ->

    restrict: "E"
    link: (scope, elem) ->
      html = "<link rel=\"stylesheet\" ng-repeat=\"(routeCtrl, cssUrl) in routeStyles\" ng-href=\"{{cssUrl}}\" >"

      elem.append $compile(html)(scope)

      scope.routeStyles = {}

      _activeStyleSheets = {}

      _pruneInactiveStyleSheets = ->
        $log.log scope.routeStyles
        angular.forEach scope.routeStyles, (styleSheet) ->
          if !_activeStyleSheets[styleSheet]?
            $log.log "head directive - removed " + styleSheet
            delete scope.routeStyles[styleSheet]

          $log.log "head directive - active stylesheets are now:"
          $log.log scope.routeStyles[styleSheet]

      $rootScope.$on "$routeChangeStart", (e, next, current) ->
        if current and current.$$route and current.$$route.css
          current.$$route.css = [current.$$route.css] unless Array.isArray(current.$$route.css)
          angular.forEach current.$$route.css, (styleSheet) ->
            delete _activeStyleSheets[styleSheet]

        if next and next.$$route and next.$$route.css
          next.$$route.css = [next.$$route.css] unless Array.isArray(next.$$route.css)

          angular.forEach next.$$route.css, (styleSheet) ->
            scope.routeStyles[styleSheet] = styleSheet
            _activeStyleSheets[styleSheet] = styleSheet

          $log.log "head directive - active stylesheets in scope are now:"
          $log.log scope.routeStyles

        $timeout ->
          _pruneInactiveStyleSheets()
        , 1000
  ]

  headDirective
```

It should be pretty self explanatory, if not please let me know, I can add more explanation tomorrow :).

**Comment by Nitad** [comment]
Have the same issue :/

**Comment by Bill77** [comment]
@Nitad,

Here was my solution to that problem, it seemed that doing everything in one event messed with the rendering timing, so I separated the functions into the two events. That resolved our issues with it, hopefully it'll help yours.

https://github.com/Bill77/angular-route-styles/commit/382b2099940ec2bf42646ff1f01a9f5005e5d52a

**Comment by tennisgent** [comment]
@Bill77 Would you be willing to do a PR from your fork to this one with that code fix so everyone can take advantage of it?

PS. Sorry this has taken me so long to get to....

**Comment by Bill77** [comment]
@tennisgent Sure, Zach, happy to help. I believe this might be my first "public" contribution. Hopefully I did it right. :)

**Comment by tennisgent** [comment]
Looks great and you did exactly what I was hoping :smile: . I think we can finally close this issue.
