### ISSUE TITLE
Demo Not Working

### ISSUE THREAD

**Issue by ciacob** [tennisgent/angular-route-styles#19]
Just cloned 621207c698695ab74eaa0cff06317ca6b4209627, and the demo is not running in my Google Chrome Version 44.0.2403.157 m on Windows 7. I'm accessing the demo via the file:/// protocol. 

Issue: the style does not change, despite the fact that some DOM manipulation is visible in the web tools panel.

**Comment by tennisgent** [comment]
Hi @ciacob , can you provide me with a little more information? Can you create a Plunker or a JSFiddle with an example of what you're seeing? Do you see any errors in your console? Do the `<link>` tags get added to the `<head>`? Are there requests in the Network tab for your extra css files?

I don't know where to start if I don't have more information. I know several others have used that very hash you're using and they say it works great.

**Comment by ciacob** [comment]
It's a cross-domain error of some sort. When accessing the files over the http:// protocol (i.e., served via some local server) everything works as expected (except CSS files previously added never get removed, but that is a different issue).

Seemingly your library cannot work when accessed over the file:/// protocol (double-clicking on the index.html file, as opposed to serving it from a web server).

Error:
XMLHttpRequest cannot load file:///C:/Users/claudius.iacob/Documents/_PROJECTS/angular-route-styles/angular-route-styles/demo/partials/partial1.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

This seems more like a limitation in Chrome and/or Angular than in your code, so maybe we should close down this issue. Cannot provide a JSFiddle, you must be accessing the file locally (via the file:/// protocol) to see the things break.

**Comment by tennisgent** [comment]
Yeah, It sounds like a CORS problem when your browser tries to access the files. I'm going to close this issue for now.
