### ISSUE TITLE
why i can't loading css

### ISSUE THREAD

**Issue by callmesoul** [tennisgent/angular-route-styles#22]
`'use strict';

/**
 * @ngdoc overview
 * @name nodejsAngularApp
 * @description
 * # nodejsAngularApp
 *
 * Main module of the application.
 */
angular
  .module('nodejsAngularApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
      'ui.router',
      'routeStyles',
      'ui.bootstrap'

  ])
  .config(function($stateProvider, $urlRouterProvider) {
      //
      // For any unmatched url, redirect to /state1
      $urlRouterProvider.otherwise("/index");
      //
      // Now set up the states
      $stateProvider
          .state('login', {
              url: "/login",
              templateUrl: "views/login.html",
              controller: 'LoginCtrl',
              css:'styles/login.css',
              controllerAs:'login'

          })
          .state('register', {
              url: "/resgiter",
              templateUrl: "views/register.html",
              controller: 'RegisterCtrl',
              controllerAs:'register',
              css:'styles/login.css'
          })
          .state('app', {
              templateUrl: "views/main.html",
              controller: 'MainCtrl',
              controllerAs: 'main'
          })
          .state('app.index', {
              url: "/index",
              templateUrl: "views/index.html",
              controller: 'IndexCtrl',
              controllerAs:'index'
          })
          .state('app.user', {
              url: "/user",
              templateUrl: "views/user/index.html",
              controller: 'UserIndexCtrl',
              controllerAs:'user/index'
          })
          .state('app.course', {
              url: "/user",
              templateUrl: "views/course/index.html",
              controller: 'CourseIndexCtrl',
              controllerAs:'course/index'
          })
  });

`

**Comment by tennisgent** [comment]
You're using Angular-UI Router, which is not supported by this library. This library only works with Angular's native `$routeProvider`. You won't be able to use this library within your project.
