### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by alexandre-payday** [tennisgent/angular-route-styles#24]
I am pretty sure because the CSS is loaded dynamically, angular does not kick in fast enough and I get the new HTML without CSS every time I change routes.

My angular.js is loaded in head tag, ng-app is on HTML tag, but tried every other way too. Tried with ng-cloak also. Am I missing something?

Thank you.

**Comment by tennisgent** [comment]
I believe your CSS isn't being served up quickly enough. The CSS is all loaded asynchronously and therefore if it takes too long for your CSS to be downloaded and parsed, then you're going to see some flickering. 

There's nothing you can do in terms of cloaking it or anything like that. It's not an angular issue. It's an issue with your CSS. You might get some slightly better performance with [AngularCSS](http://www.door3.com/articles/work/introducing-angularcss-css-demand-angularjs) but I don't know for sure. 

Regardless, there isn't much we can do for you here. If there's no way to speed up your style loading/rendering, then this little library isn't going to help you very much.

**Comment by alexandre-payday** [comment]
Thank you. I tried betsol library too, which is supposed to use resolve, but I think you are right and my front-end developer is abusing of the css length. Thank you
