### ISSUE TITLE
UI-route

### ISSUE THREAD

**Issue by agasthyanavaneeth** [tennisgent/angular-route-styles#8]
Does it work with ui-route?

**Comment by tennisgent** [comment]
No. UI-Router uses a whole different system for passing route states, so this code will not work for that. This only works with Angular's native `$routeProvider` routing system.

**Comment by agasthyanavaneeth** [comment]
Probably adding support for ui-route should be very good! (At least, a completely different variant should also be fine)
Anyways, closing the issue.
